### ISSUE TITLE
Notifications Dropdown & Likes missing tweaks

### ISSUE THREAD

**Issue by SalbugVR** [Metamaniac/VRCWebTweaks#1]
The dropdown for notifications and the pop-up window for likes are missing most of the visual tweaks.

![image](https://user-images.githubusercontent.com/24326270/185363014-05be60bc-a43b-49d4-bf83-f8da20bd4ba2.png)

![image](https://user-images.githubusercontent.com/24326270/185363084-481a9979-9f3b-4986-ab8c-4ee1e6e6790d.png)

**Comment by Metamaniac** [comment]
I'm aware haha, still haven't gotten around to touching that yet (have a tab open profiling it)

**Comment by Metamaniac** [comment]
https://github.com/Metamaniac/VRCWebTweaks/commit/9db553ae19ca2cf8e92e10e9db938af96e8e3e08
